# Generated by Django 3.2.2 on 2021-07-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_header_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='header_image',
        ),
    ]
