# Generated by Django 3.2.2 on 2021-07-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210702_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
    ]
